import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:smart_expense_tracker/features/expenses/domain/entities/expense_entity.dart';
import 'package:smart_expense_tracker/core/utils/utils.dart'; // For formatting

class ExportService {
  static Future<void> exportExpensesToCSV(List<ExpenseEntity> expenses) async {
    final header = 'Date,Category,Amount,Note,ID\n';

    final buffer = StringBuffer();
    buffer.write(header);

    for (final expense in expenses) {
      final line = [
        DateUtils.formatDate(expense.date),
        expense.category,
        expense.amount.toStringAsFixed(2),
        expense.note?.replaceAll(',', ' ') ?? '', // Escape commas
        expense.id,
      ].join(',');
      buffer.writeln(line);
    }

    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/expenses_export.csv');
    await file.writeAsString(buffer.toString());

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Here is my expense report generated by Smart Expense Tracker Pro',
    );
  }
}
